# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import geometry_pb2 as proto_dot_geometry__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/geometry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalysisServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeState = channel.unary_unary(
                '/geometry.AnalysisService/AnalyzeState',
                request_serializer=proto_dot_geometry__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=proto_dot_geometry__pb2.AnalysisResponse.FromString,
                _registered_method=True)
        self.StreamState = channel.stream_stream(
                '/geometry.AnalysisService/StreamState',
                request_serializer=proto_dot_geometry__pb2.AnalysisRequest.SerializeToString,
                response_deserializer=proto_dot_geometry__pb2.AnalysisResponse.FromString,
                _registered_method=True)


class AnalysisServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeState(self, request, context):
        """Unary call for a single notebook execution request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request_iterator, context):
        """Bidirectional streaming for continuous 60fps canvas dragging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeState': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeState,
                    request_deserializer=proto_dot_geometry__pb2.AnalysisRequest.FromString,
                    response_serializer=proto_dot_geometry__pb2.AnalysisResponse.SerializeToString,
            ),
            'StreamState': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=proto_dot_geometry__pb2.AnalysisRequest.FromString,
                    response_serializer=proto_dot_geometry__pb2.AnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geometry.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geometry.AnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalysisService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geometry.AnalysisService/AnalyzeState',
            proto_dot_geometry__pb2.AnalysisRequest.SerializeToString,
            proto_dot_geometry__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/geometry.AnalysisService/StreamState',
            proto_dot_geometry__pb2.AnalysisRequest.SerializeToString,
            proto_dot_geometry__pb2.AnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
