# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: geometry.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egeometry.proto\x12\x08geometry\"*\n\x0eGeometricState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"=\n\nJointState\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x61ngle\x18\x02 \x01(\x02\x12\x12\n\nmotor_data\x18\x03 \x03(\x02\"y\n\nRobotState\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12$\n\x06joints\x18\x02 \x03(\x0b\x32\x14.geometry.JointState\x12\x33\n\x11\x65nd_effector_pose\x18\x03 \x01(\x0b\x32\x18.geometry.GeometricState\"\x84\x01\n\x0f\x41nalysisRequest\x12\x0f\n\x07\x63ontext\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12)\n\x07objects\x18\x03 \x03(\x0b\x32\x18.geometry.GeometricState\x12#\n\x05robot\x18\x04 \x01(\x0b\x32\x14.geometry.RobotState\"U\n\x10\x41nalysisResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12#\n\x05robot\x18\x03 \x01(\x0b\x32\x14.geometry.RobotState2\xa2\x01\n\x0f\x41nalysisService\x12\x45\n\x0c\x41nalyzeState\x12\x19.geometry.AnalysisRequest\x1a\x1a.geometry.AnalysisResponse\x12H\n\x0bStreamState\x12\x19.geometry.AnalysisRequest\x1a\x1a.geometry.AnalysisResponse(\x01\x30\x01\x42\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_GEOMETRICSTATE']._serialized_start=28
  _globals['_GEOMETRICSTATE']._serialized_end=70
  _globals['_JOINTSTATE']._serialized_start=72
  _globals['_JOINTSTATE']._serialized_end=133
  _globals['_ROBOTSTATE']._serialized_start=135
  _globals['_ROBOTSTATE']._serialized_end=256
  _globals['_ANALYSISREQUEST']._serialized_start=259
  _globals['_ANALYSISREQUEST']._serialized_end=391
  _globals['_ANALYSISRESPONSE']._serialized_start=393
  _globals['_ANALYSISRESPONSE']._serialized_end=478
  _globals['_ANALYSISSERVICE']._serialized_start=481
  _globals['_ANALYSISSERVICE']._serialized_end=643
# @@protoc_insertion_point(module_scope)
