// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/geometry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A geometric multivector representing physical state
type GeometricState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []float32              `protobuf:"fixed32,2,rep,packed,name=data,proto3" json:"data,omitempty"` // e.g. [scalar, e1, e2, e3, e12, e23, e31, e123]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeometricState) Reset() {
	*x = GeometricState{}
	mi := &file_proto_geometry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeometricState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeometricState) ProtoMessage() {}

func (x *GeometricState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geometry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeometricState.ProtoReflect.Descriptor instead.
func (*GeometricState) Descriptor() ([]byte, []int) {
	return file_proto_geometry_proto_rawDescGZIP(), []int{0}
}

func (x *GeometricState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GeometricState) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type AnalysisRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Objects       []*GeometricState      `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisRequest) Reset() {
	*x = AnalysisRequest{}
	mi := &file_proto_geometry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisRequest) ProtoMessage() {}

func (x *AnalysisRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geometry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisRequest.ProtoReflect.Descriptor instead.
func (*AnalysisRequest) Descriptor() ([]byte, []int) {
	return file_proto_geometry_proto_rawDescGZIP(), []int{1}
}

func (x *AnalysisRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *AnalysisRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AnalysisRequest) GetObjects() []*GeometricState {
	if x != nil {
		return x.Objects
	}
	return nil
}

type AnalysisResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"` // Return the generated analysis code or physical properties
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalysisResponse) Reset() {
	*x = AnalysisResponse{}
	mi := &file_proto_geometry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResponse) ProtoMessage() {}

func (x *AnalysisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_geometry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResponse.ProtoReflect.Descriptor instead.
func (*AnalysisResponse) Descriptor() ([]byte, []int) {
	return file_proto_geometry_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AnalysisResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_proto_geometry_proto protoreflect.FileDescriptor

const file_proto_geometry_proto_rawDesc = "" +
	"\n" +
	"\x14proto/geometry.proto\x12\bgeometry\"4\n" +
	"\x0eGeometricState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x03(\x02R\x04data\"{\n" +
	"\x0fAnalysisRequest\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x122\n" +
	"\aobjects\x18\x03 \x03(\v2\x18.geometry.GeometricStateR\aobjects\">\n" +
	"\x10AnalysisResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code2\xa2\x01\n" +
	"\x0fAnalysisService\x12E\n" +
	"\fAnalyzeState\x12\x19.geometry.AnalysisRequest\x1a\x1a.geometry.AnalysisResponse\x12H\n" +
	"\vStreamState\x12\x19.geometry.AnalysisRequest\x1a\x1a.geometry.AnalysisResponse(\x010\x01B9Z7github.com/iig/sensensblegeometry/backend/gateway/protob\x06proto3"

var (
	file_proto_geometry_proto_rawDescOnce sync.Once
	file_proto_geometry_proto_rawDescData []byte
)

func file_proto_geometry_proto_rawDescGZIP() []byte {
	file_proto_geometry_proto_rawDescOnce.Do(func() {
		file_proto_geometry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_geometry_proto_rawDesc), len(file_proto_geometry_proto_rawDesc)))
	})
	return file_proto_geometry_proto_rawDescData
}

var file_proto_geometry_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_geometry_proto_goTypes = []any{
	(*GeometricState)(nil),   // 0: geometry.GeometricState
	(*AnalysisRequest)(nil),  // 1: geometry.AnalysisRequest
	(*AnalysisResponse)(nil), // 2: geometry.AnalysisResponse
}
var file_proto_geometry_proto_depIdxs = []int32{
	0, // 0: geometry.AnalysisRequest.objects:type_name -> geometry.GeometricState
	1, // 1: geometry.AnalysisService.AnalyzeState:input_type -> geometry.AnalysisRequest
	1, // 2: geometry.AnalysisService.StreamState:input_type -> geometry.AnalysisRequest
	2, // 3: geometry.AnalysisService.AnalyzeState:output_type -> geometry.AnalysisResponse
	2, // 4: geometry.AnalysisService.StreamState:output_type -> geometry.AnalysisResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_geometry_proto_init() }
func file_proto_geometry_proto_init() {
	if File_proto_geometry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_geometry_proto_rawDesc), len(file_proto_geometry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_geometry_proto_goTypes,
		DependencyIndexes: file_proto_geometry_proto_depIdxs,
		MessageInfos:      file_proto_geometry_proto_msgTypes,
	}.Build()
	File_proto_geometry_proto = out.File
	file_proto_geometry_proto_goTypes = nil
	file_proto_geometry_proto_depIdxs = nil
}
