<script lang="ts">
  /**
   * GNCCodeInspector.svelte
   * Editable, syntax-highlighted JAX/Python code preview.
   * Generates code from the current network architecture.
   * Allows inline editing before GCP export.
   */

  interface NetworkLayer {
    type: string;
    nodes: number;
    grades: { scalar: boolean; vector: boolean; bivector: boolean; trivector: boolean; };
    tau: number;
    activation: string;
  }

  let {
    layers = [] as NetworkLayer[],
    trainingState = {} as any,
    onClose = () => {},
    onExport = (_code: string) => {},
  } = $props();

  let editableCode = $state('');
  let activeTab = $state<'jax' | 'vhdl' | 'schema'>('jax');
  let copied = $state(false);

  function gradesDim(grades: NetworkLayer['grades']): number {
    return (grades.scalar ? 1 : 0) + (grades.vector ? 3 : 0) + (grades.bivector ? 3 : 0) + (grades.trivector ? 1 : 0);
  }

  function generateJAX(layers: NetworkLayer[]): string {
    const lines: string[] = [];
    lines.push('"""');
    lines.push('Clifford-Liquid Time-Constant Network — Auto-Generated by Geometric NC Studio');
    lines.push('Architecture: Cl(3,0) Equivariant Neural Network');
    lines.push(`Generated: ${new Date().toISOString()}`);
    lines.push('"""');
    lines.push('');
    lines.push('import jax');
    lines.push('import jax.numpy as jnp');
    lines.push('import flax.linen as nn');
    lines.push('from typing import Sequence');
    lines.push('');
    lines.push('# ── Clifford Geometric Product (Cl(3,0)) ─────────────────────────────────');
    lines.push('def clifford_product(a: jnp.ndarray, b: jnp.ndarray) -> jnp.ndarray:');
    lines.push('    """Full geometric product in Cl(3,0)."""');
    lines.push('    # a, b are [batch, 8] multivectors: [s, e1, e2, e3, e12, e23, e31, e123]');
    lines.push('    # Grade-structured geometric product (see Hestenes, New Foundations)');
    lines.push('    s,e1,e2,e3,e12,e23,e31,e123 = [a[:,i] for i in range(8)]');
    lines.push('    t,f1,f2,f3,f12,f23,f31,f123 = [b[:,i] for i in range(8)]');
    lines.push('    res = jnp.stack([');
    lines.push('        s*t + e1*f1 + e2*f2 + e3*f3 - e12*f12 - e23*f23 - e31*f31 - e123*f123,');
    lines.push('        s*f1 + e1*t - e2*f12 + e3*f31 + e12*f2 - e23*f123 - e31*f3 - e123*f23,');
    lines.push('        s*f2 + e1*f12 + e2*t - e3*f23 - e12*f1 + e23*f3 - e31*f123 - e123*f31,');
    lines.push('        s*f3 - e1*f31 + e2*f23 + e3*t - e12*f123 - e23*f2 + e31*f1 - e123*f12,');
    lines.push('        s*f12 + e1*f2 - e2*f1 + e3*f123 + e12*t - e23*f31 + e31*f23 + e123*f3,');
    lines.push('        s*f23 + e1*f123 + e2*f3 - e3*f2 + e12*f31 + e23*t - e31*f12 + e123*f1,');
    lines.push('        s*f31 - e1*f3 + e2*f123 + e3*f1 - e12*f23 + e23*f12 + e31*t + e123*f2,');
    lines.push('        s*f123 + e1*f23 + e2*f31 + e3*f12 + e12*f3 + e23*f1 + e31*f2 + e123*t,');
    lines.push('    ], axis=-1)');
    lines.push('    return res');
    lines.push('');
    lines.push('# ── Activation ───────────────────────────────────────────────────────────');
    lines.push('def geometric_sigmoid(x: jnp.ndarray) -> jnp.ndarray:');
    lines.push('    return jax.nn.sigmoid(x) - 0.5');
    lines.push('');
    lines.push('# ── Network Architecture ─────────────────────────────────────────────────');
    lines.push('class CliffordLTCNetwork(nn.Module):');
    lines.push(`    """${layers.length}-layer Clifford-LTC Network in Cl(3,0)"""`);
    lines.push('');

    layers.forEach((layer, i) => {
      const dim = gradesDim(layer.grades);
      lines.push(`    # Layer ${i}: ${layer.type} (${layer.nodes} nodes, grade_dim=${dim})`);
      if (layer.type === 'ltc_recurrent') {
        lines.push(`    ltc_w${i}: jnp.ndarray = nn.initializers.glorot_normal()(jax.random.PRNGKey(${i}), (${layer.nodes}, ${dim}, 8))`);
        lines.push(`    ltc_tau${i}: float = ${layer.tau}`);
      } else if (layer.type !== 'input') {
        lines.push(`    w${i}: jnp.ndarray = nn.initializers.glorot_normal()(jax.random.PRNGKey(${i}), (${layer.nodes}, ${dim}, 8))`);
      }
    });

    lines.push('');
    lines.push('    @nn.compact');
    lines.push('    def __call__(self, x: jnp.ndarray, hidden: jnp.ndarray, dt: float) -> tuple:');
    lines.push('        """');
    lines.push('        Forward pass with continuous-time Fused ODE solver.');
    lines.push('        Args:');
    lines.push('            x: Input multivector [batch, 8]');
    lines.push('            hidden: Recurrent hidden state [batch, nodes, 8]');
    lines.push('            dt: ODE step size');
    lines.push('        Returns: (output_mv, new_hidden)');
    lines.push('        """');

    layers.filter(l => l.type === 'ltc_recurrent').forEach((layer, i) => {
      lines.push(`        # LTC Fused Euler: x(t+dt) = x + dt*(-x/tau + f(x,I))`);
      lines.push(`        f_coupling = clifford_product(self.ltc_w${i}, x)`);
      lines.push(`        f_val = geometric_sigmoid(f_coupling + hidden[:, ${i}])`);
      lines.push(`        hidden_new = hidden.at[:, ${i}].set(`);
      lines.push(`            hidden[:, ${i}] + dt * (-hidden[:, ${i}] / self.ltc_tau${i} + f_val)`);
      lines.push(`        )`);
    });

    lines.push('        return hidden_new[:, -1], hidden_new');
    lines.push('');
    lines.push('# ── RL Training Loop (GCP TPU) ───────────────────────────────────────────');
    lines.push('def train_step(params, batch, lr):');
    lines.push('    def loss_fn(params):');
    lines.push('        # Structural Strain Loss: minimize node displacement under cyclogenesis');
    lines.push('        pred, _ = CliffordLTCNetwork().apply(params, batch["wind"], batch["hidden"], batch["dt"])');
    lines.push('        strain = jnp.mean(jnp.sum((pred - batch["target"]) ** 2, axis=-1))');
    lines.push('        equiv_error = jnp.mean(jnp.abs(jnp.linalg.norm(pred, axis=-1) - jnp.linalg.norm(batch["target"], axis=-1)))');
    lines.push('        return strain + 0.1 * equiv_error');
    lines.push('    grads = jax.grad(loss_fn)(params)');
    lines.push('    return jax.tree_util.tree_map(lambda p, g: p - lr * g, params, grads)');
    return lines.join('\n');
  }

  function generateVHDL(layers: NetworkLayer[]): string {
    return `-- VHDL Skeleton: Clifford-LTC Network (Geometric NC Export)
-- Target: FPGA Neuromorphic Hardware
-- Precision: Fixed-Point Q8.8

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity CliffordLTC is
    generic (
        NUM_LAYERS  : integer := ${layers.length};
        MV_DIM      : integer := 8;   -- Cl(3,0) multivector dimension
        FIXED_BITS  : integer := 16   -- Q8.8 fixed-point
    );
    port (
        clk        : in  STD_LOGIC;
        rst        : in  STD_LOGIC;
        wind_mv_in : in  STD_LOGIC_VECTOR(MV_DIM * FIXED_BITS - 1 downto 0);
        ctrl_out   : out STD_LOGIC_VECTOR(MV_DIM * FIXED_BITS - 1 downto 0)
    );
end CliffordLTC;

architecture Behavioral of CliffordLTC is
${layers.filter(l => l.type === 'ltc_recurrent').map((l, i) =>
  `    signal hidden_${i} : STD_LOGIC_VECTOR(${l.nodes} * MV_DIM * FIXED_BITS - 1 downto 0);`
).join('\n')}
begin
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                ${layers.filter(l => l.type === 'ltc_recurrent').map((_,i) => `hidden_${i} <= (others => '0');`).join(' ')}
            else
                -- Fused ODE Euler step per LTC layer
                -- Implementation: Clifford geometric product via LUT or DSP blocks
                null;  -- TODO: Full geometric product pipeline
            end if;
        end if;
    end process;
end Behavioral;
`;
  }

  function generateSchema(layers: NetworkLayer[]): string {
    return JSON.stringify({
      type: 'CliffordLiquidTimeConstantNetwork',
      framework: 'JAX/Flax',
      geometry: 'Cl(3,0)',
      equivariant: true,
      training_state: trainingState,
      layers: layers.map((l, i) => ({
        index: i,
        type: l.type,
        nodes: l.nodes,
        grade_dim: gradesDim(l.grades),
        grades: l.grades,
        tau: l.tau,
        activation: l.activation,
      })),
    }, null, 2);
  }

  $effect(() => {
    if (activeTab === 'jax') editableCode = generateJAX(layers);
    else if (activeTab === 'vhdl') editableCode = generateVHDL(layers);
    else editableCode = generateSchema(layers);
  });

  function handleExport() {
    onExport(editableCode);
    const blob = new Blob([editableCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = activeTab === 'jax' ? 'gnc_model.py' : activeTab === 'vhdl' ? 'gnc_model.vhd' : 'gnc_schema.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(editableCode).then(() => {
      copied = true;
      setTimeout(() => copied = false, 1500);
    });
  }
</script>

<div class="inspector">
  <div class="inspector-header">
    <span class="inspector-title">Code Inspector</span>
    <div class="tab-row">
      <button class="tab-btn" class:active={activeTab === 'jax'}  onclick={() => activeTab = 'jax'}>JAX/Python</button>
      <button class="tab-btn" class:active={activeTab === 'vhdl'} onclick={() => activeTab = 'vhdl'}>VHDL</button>
      <button class="tab-btn" class:active={activeTab === 'schema'} onclick={() => activeTab = 'schema'}>Schema</button>
    </div>
    <button class="close-btn" onclick={onClose}>×</button>
  </div>

  <textarea class="code-editor" spellcheck="false" bind:value={editableCode}></textarea>

  <div class="inspector-footer">
    <span class="inspector-hint">Edit code before exporting</span>
    <div class="footer-actions">
      <button class="action-btn copy" onclick={copyToClipboard}>{copied ? 'Copied!' : 'Copy'}</button>
      <button class="action-btn export" onclick={handleExport}>Download</button>
    </div>
  </div>
</div>

<style>
  .inspector {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: #0d1117;
    border-radius: 10px;
    border: 1px solid rgba(255,255,255,0.08);
    overflow: hidden;
  }

  .inspector-header {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 14px;
    border-bottom: 1px solid rgba(255,255,255,0.06);
    flex-shrink: 0;
  }

  .inspector-title {
    font-size: 0.7rem;
    font-weight: 700;
    letter-spacing: 0.1em;
    text-transform: uppercase;
    color: #94a3b8;
    flex-shrink: 0;
  }

  .tab-row {
    display: flex;
    gap: 2px;
    background: rgba(0,0,0,0.3);
    border-radius: 6px;
    padding: 2px;
  }

  .tab-btn {
    padding: 3px 10px;
    border: none;
    border-radius: 5px;
    background: transparent;
    font-size: 0.67rem;
    color: rgba(255,255,255,0.35);
    cursor: pointer;
    font-family: monospace;
    transition: all 0.15s;
  }
  .tab-btn.active { background: rgba(255,255,255,0.1); color: #e2e8f0; }

  .close-btn {
    margin-left: auto;
    width: 22px; height: 22px;
    border: none;
    border-radius: 5px;
    background: rgba(239,68,68,0.12);
    color: #ef4444;
    font-size: 1rem;
    cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    flex-shrink: 0;
  }
  .close-btn:hover { background: rgba(239,68,68,0.25); }

  .code-editor {
    flex: 1;
    width: 100%;
    background: transparent;
    border: none;
    outline: none;
    resize: none;
    padding: 14px 16px;
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
    font-size: 0.68rem;
    line-height: 1.6;
    color: #a6e3a1;
    tab-size: 4;
  }

  .inspector-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 8px 14px;
    border-top: 1px solid rgba(255,255,255,0.06);
    flex-shrink: 0;
  }

  .inspector-hint {
    font-size: 0.62rem;
    color: #475569;
    font-family: monospace;
  }

  .footer-actions { display: flex; gap: 8px; }

  .action-btn {
    padding: 5px 14px;
    border-radius: 6px;
    border: 1px solid;
    font-size: 0.7rem;
    cursor: pointer;
    font-family: inherit;
    transition: all 0.15s;
  }
  .action-btn.copy {
    background: rgba(255,255,255,0.05);
    border-color: rgba(255,255,255,0.1);
    color: rgba(255,255,255,0.6);
  }
  .action-btn.copy:hover { background: rgba(255,255,255,0.1); color: #fff; }
  .action-btn.export {
    background: rgba(79,70,229,0.3);
    border-color: #6366f1;
    color: #c7d2fe;
  }
  .action-btn.export:hover { background: rgba(79,70,229,0.5); }
</style>
