<script lang="ts">
  /**
   * GNCCodeInspector.svelte
   * Editable, syntax-highlighted JAX/Python code preview.
   * Generates code from the current network architecture.
   * Allows inline editing before GCP export.
   */

  interface NetworkLayer {
    type: string;
    nodes: number;
    grades: { scalar: boolean; vector: boolean; bivector: boolean; trivector: boolean; };
    tau: number;
    activation: string;
  }

  interface Props {
    layers?: NetworkLayer[];
    trainingState?: any;
    onClose?: () => void;
    onExport?: (code: string) => void;
  }

  let {
    layers = [] as NetworkLayer[],
    trainingState = {} as any,
    onClose = () => {},
    onExport = (_code: string) => {},
  }: Props = $props();

  let editableCode = $state('');
  let activeTab = $state<'jax' | 'vhdl' | 'schema'>('jax');
  let copied = $state(false);
  let isMaximized = $state(false);
  let fontSize = $state(13);
  let wordWrap = $state(false);

  let lineCount = $derived(editableCode.split('\n').length);
  let lineNumbers = $derived(Array.from({ length: lineCount }, (_, i) => i + 1));

  function gradesDim(grades: NetworkLayer['grades']): number {
    return (grades.scalar ? 1 : 0) + (grades.vector ? 3 : 0) + (grades.bivector ? 3 : 0) + (grades.trivector ? 1 : 0);
  }

  function generateJAX(layers: NetworkLayer[]): string {
    const lines: string[] = [];
    lines.push('"""');
    lines.push('Clifford-Liquid Time-Constant Network — Auto-Generated by Geometric NC Studio');
    lines.push('Architecture: Cl(3,0) Equivariant Neural Network');
    lines.push(`Generated: ${new Date().toISOString()}`);
    lines.push('"""');
    lines.push('');
    lines.push('import jax');
    lines.push('import jax.numpy as jnp');
    lines.push('import flax.linen as nn');
    lines.push('from typing import Sequence');
    lines.push('');
    lines.push('# ── Clifford Geometric Product (Cl(3,0)) ─────────────────────────────────');
    lines.push('def clifford_product(a: jnp.ndarray, b: jnp.ndarray) -> jnp.ndarray:');
    lines.push('    """Full geometric product in Cl(3,0)."""');
    lines.push('    # a, b are [batch, 8] multivectors: [s, e1, e2, e3, e12, e23, e31, e123]');
    lines.push('    # Grade-structured geometric product (see Hestenes, New Foundations)');
    lines.push('    s,e1,e2,e3,e12,e23,e31,e123 = [a[:,i] for i in range(8)]');
    lines.push('    t,f1,f2,f3,f12,f23,f31,f123 = [b[:,i] for i in range(8)]');
    lines.push('    res = jnp.stack([');
    lines.push('        s*t + e1*f1 + e2*f2 + e3*f3 - e12*f12 - e23*f23 - e31*f31 - e123*f123,');
    lines.push('        s*f1 + e1*t - e2*f12 + e3*f31 + e12*f2 - e23*f123 - e31*f3 - e123*f23,');
    lines.push('        s*f2 + e1*f12 + e2*t - e3*f23 - e12*f1 + e23*f3 - e31*f123 - e123*f31,');
    lines.push('        s*f3 - e1*f31 + e2*f23 + e3*t - e12*f123 - e23*f2 + e31*f1 - e123*f12,');
    lines.push('        s*f12 + e1*f2 - e2*f1 + e3*f123 + e12*t - e23*f31 + e31*f23 + e123*f3,');
    lines.push('        s*f23 + e1*f123 + e2*f3 - e3*f2 + e12*f31 + e23*t - e31*f12 + e123*f1,');
    lines.push('        s*f31 - e1*f3 + e2*f123 + e3*f1 - e12*f23 + e23*f12 + e31*t + e123*f2,');
    lines.push('        s*f123 + e1*f23 + e2*f31 + e3*f12 + e12*f3 + e23*f1 + e31*f2 + e123*t,');
    lines.push('    ], axis=-1)');
    lines.push('    return res');
    lines.push('');
    lines.push('# ── Activation ───────────────────────────────────────────────────────────');
    lines.push('def geometric_sigmoid(x: jnp.ndarray) -> jnp.ndarray:');
    lines.push('    return jax.nn.sigmoid(x) - 0.5');
    lines.push('');
    lines.push('# ── Network Architecture ─────────────────────────────────────────────────');
    lines.push('class CliffordLTCNetwork(nn.Module):');
    lines.push(`    """${layers.length}-layer Clifford-LTC Network in Cl(3,0)"""`);
    lines.push('');

    layers.forEach((layer, i) => {
      const dim = gradesDim(layer.grades);
      lines.push(`    # Layer ${i}: ${layer.type} (${layer.nodes} nodes, grade_dim=${dim})`);
      if (layer.type === 'ltc_recurrent') {
        lines.push(`    ltc_w${i}: jnp.ndarray = nn.initializers.glorot_normal()(jax.random.PRNGKey(${i}), (${layer.nodes}, ${dim}, 8))`);
        lines.push(`    ltc_tau${i}: float = ${layer.tau}`);
      } else if (layer.type !== 'input') {
        lines.push(`    w${i}: jnp.ndarray = nn.initializers.glorot_normal()(jax.random.PRNGKey(${i}), (${layer.nodes}, ${dim}, 8))`);
      }
    });

    lines.push('');
    lines.push('    @nn.compact');
    lines.push('    def __call__(self, x: jnp.ndarray, hidden: jnp.ndarray, dt: float) -> tuple:');
    lines.push('        """');
    lines.push('        Forward pass with continuous-time Fused ODE solver.');
    lines.push('        Args:');
    lines.push('            x: Input multivector [batch, 8]');
    lines.push('            hidden: Recurrent hidden state [batch, nodes, 8]');
    lines.push('            dt: ODE step size');
    lines.push('        Returns: (output_mv, new_hidden)');
    lines.push('        """');

    layers.filter(l => l.type === 'ltc_recurrent').forEach((layer, i) => {
      lines.push(`        # LTC Fused Euler: x(t+dt) = x + dt*(-x/tau + f(x,I))`);
      lines.push(`        f_coupling = clifford_product(self.ltc_w${i}, x)`);
      lines.push(`        f_val = geometric_sigmoid(f_coupling + hidden[:, ${i}])`);
      lines.push(`        hidden_new = hidden.at[:, ${i}].set(`);
      lines.push(`            hidden[:, ${i}] + dt * (-hidden[:, ${i}] / self.ltc_tau${i} + f_val)`);
      lines.push(`        )`);
    });

    lines.push('        return hidden_new[:, -1], hidden_new');
    lines.push('');
    lines.push('# ── RL Training Loop (GCP TPU) ───────────────────────────────────────────');
    lines.push('def train_step(params, batch, lr):');
    lines.push('    def loss_fn(params):');
    lines.push('        # Structural Strain Loss: minimize node displacement under cyclogenesis');
    lines.push('        pred, _ = CliffordLTCNetwork().apply(params, batch["wind"], batch["hidden"], batch["dt"])');
    lines.push('        strain = jnp.mean(jnp.sum((pred - batch["target"]) ** 2, axis=-1))');
    lines.push('        equiv_error = jnp.mean(jnp.abs(jnp.linalg.norm(pred, axis=-1) - jnp.linalg.norm(batch["target"], axis=-1)))');
    lines.push('        return strain + 0.1 * equiv_error');
    lines.push('    grads = jax.grad(loss_fn)(params)');
    lines.push('    return jax.tree_util.tree_map(lambda p, g: p - lr * g, params, grads)');
    return lines.join('\n');
  }

  import { generateVHDLMultivectorMultiplier } from '../physics/VHDLExporter';

  function generateVHDL(_layers: NetworkLayer[]): string {
    return generateVHDLMultivectorMultiplier();
  }

  function generateSchema(layers: NetworkLayer[]): string {
    return JSON.stringify({
      type: 'CliffordLiquidTimeConstantNetwork',
      framework: 'JAX/Flax',
      geometry: 'Cl(3,0)',
      equivariant: true,
      training_state: trainingState,
      layers: layers.map((l, i) => ({
        index: i,
        type: l.type,
        nodes: l.nodes,
        grade_dim: gradesDim(l.grades),
        grades: l.grades,
        tau: l.tau,
        activation: l.activation,
      })),
    }, null, 2);
  }

  $effect(() => {
    if (activeTab === 'jax') editableCode = generateJAX(layers);
    else if (activeTab === 'vhdl') editableCode = generateVHDL(layers);
    else editableCode = generateSchema(layers);
  });

  function handleExport() {
    onExport(editableCode);
    const blob = new Blob([editableCode], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = activeTab === 'jax' ? 'gnc_model.py' : activeTab === 'vhdl' ? 'gnc_model.vhd' : 'gnc_schema.json';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(editableCode).then(() => {
      copied = true;
      setTimeout(() => copied = false, 1500);
    });
  }
</script>

<div class="inspector" class:maximized={isMaximized}>
  <div class="inspector-header">
    <span class="inspector-title">Code Inspector</span>
    
    <div class="tab-row">
      <button class="tab-btn" class:active={activeTab === 'jax'}  onclick={() => activeTab = 'jax'}>JAX/Python</button>
      <button class="tab-btn" class:active={activeTab === 'vhdl'} onclick={() => activeTab = 'vhdl'}>VHDL</button>
      <button class="tab-btn" class:active={activeTab === 'schema'} onclick={() => activeTab = 'schema'}>Schema</button>
    </div>

    <!-- IDE Controls -->
    <div class="editor-controls">
      <button class="ctrl-btn" onclick={() => wordWrap = !wordWrap} class:active={wordWrap} title="Toggle Word Wrap">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M3 12h15a3 3 0 1 1 0 6h-4M3 18h7M16 16l-2 2 2 2"/></svg>
      </button>
      <div class="zoom-controls">
        <button class="ctrl-btn" onclick={() => fontSize = Math.max(10, fontSize - 1)} title="Decrease Font Size">-</button>
        <span class="zoom-val">{fontSize}px</span>
        <button class="ctrl-btn" onclick={() => fontSize = Math.min(20, fontSize + 1)} title="Increase Font Size">+</button>
      </div>
    </div>

    <div class="header-actions">
      <button class="icon-btn" onclick={() => isMaximized = !isMaximized} title={isMaximized ? "Restore Size" : "Maximize IDE"}>
        {#if isMaximized}
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 3v3a2 2 0 0 1-2 2H3m18 0h-3a2 2 0 0 1-2-2V3m0 18v-3a2 2 0 0 1 2-2h3M3 16h3a2 2 0 0 1 2 2v3"/></svg>
        {:else}
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M15 3h6v6M9 21H3v-6M21 3l-7 7M3 21l7-7"/></svg>
        {/if}
      </button>
      <button class="close-btn" onclick={onClose} title="Close Code Inspector">×</button>
    </div>
  </div>

  <!-- IDE Code Body with Line Numbers -->
  <div class="code-body">
    <div class="line-gutter" style="font-size: {fontSize}px;">
      {#each lineNumbers as num}
        <span>{num}</span>
      {/each}
    </div>
    <textarea 
      class="code-editor" 
      class:wrap={wordWrap}
      spellcheck="false" 
      bind:value={editableCode}
      style="font-size: {fontSize}px;"
    ></textarea>
  </div>

  <div class="inspector-footer">
    <span class="inspector-hint">{lineCount} lines • Edit JAX/Python or VHDL code directly before exporting</span>
    <div class="footer-actions">
      <button class="action-btn copy" onclick={copyToClipboard}>{copied ? 'Copied!' : 'Copy to Clipboard'}</button>
      <button class="action-btn export" onclick={handleExport}>Download File</button>
    </div>
  </div>
</div>

<style>
  .inspector {
    display: flex;
    flex-direction: column;
    height: 100%;
    background: var(--bg-chassis);
    border-radius: 10px;
    border: 1px solid var(--card-border);
    overflow: hidden;
  }

  .inspector-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 10px 16px;
    border-bottom: 1px solid var(--card-border);
    background: var(--card-bg);
    flex-shrink: 0;
  }

  .inspector-title {
    font-size: 0.75rem;
    font-weight: 800;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: var(--accent-vis);
    flex-shrink: 0;
  }

  .tab-row {
    display: flex;
    gap: 4px;
    background: var(--panel-bg);
    border-radius: 8px;
    padding: 3px;
    border: 1px solid var(--card-border);
  }

  .tab-btn {
    padding: 4px 12px;
    border: none;
    border-radius: 6px;
    background: transparent;
    font-size: 0.7rem;
    font-weight: 600;
    color: var(--text-muted);
    cursor: pointer;
    font-family: var(--font-mono, monospace);
    transition: all 0.15s;
  }
  .tab-btn.active {
    background: rgba(16, 185, 129, 0.15);
    color: #10b981;
    font-weight: 700;
  }

  .editor-controls {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-left: auto;
  }
  
  .zoom-controls {
    display: flex;
    align-items: center;
    gap: 4px;
    background: var(--panel-bg);
    border: 1px solid var(--card-border);
    border-radius: 6px;
    padding: 2px 6px;
  }
  .zoom-val {
    font-size: 0.65rem;
    font-family: monospace;
    color: var(--text-muted);
    min-width: 28px;
    text-align: center;
  }

  .ctrl-btn {
    background: transparent;
    border: 1px solid transparent;
    color: var(--text-muted);
    border-radius: 4px;
    padding: 2px 6px;
    cursor: pointer;
    font-size: 0.7rem;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .ctrl-btn:hover { background: var(--card-border); color: var(--text-main); }
  .ctrl-btn.active { background: rgba(16, 185, 129, 0.15); color: #10b981; border-color: rgba(16, 185, 129, 0.3); }

  .header-actions {
    display: flex;
    align-items: center;
    gap: 6px;
  }

  .icon-btn {
    background: var(--panel-bg);
    border: 1px solid var(--card-border);
    color: var(--text-muted);
    border-radius: 6px;
    width: 28px;
    height: 28px;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.15s;
  }
  .icon-btn:hover { color: var(--text-main); border-color: var(--accent-vis); }

  .close-btn {
    width: 28px; height: 28px;
    border: none;
    border-radius: 6px;
    background: rgba(239,68,68,0.12);
    color: #ef4444;
    font-size: 1.1rem;
    cursor: pointer;
    display: flex; align-items: center; justify-content: center;
    flex-shrink: 0;
  }
  .close-btn:hover { background: rgba(239,68,68,0.25); }

  /* IDE Body */
  .code-body {
    flex: 1;
    display: flex;
    background: #090d16;
    overflow: hidden;
    position: relative;
  }

  .line-gutter {
    padding: 14px 10px 14px 14px;
    background: #060911;
    border-right: 1px solid #1e293b;
    color: #475569;
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
    line-height: 1.6;
    text-align: right;
    user-select: none;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  .code-editor {
    flex: 1;
    width: 100%;
    height: 100%;
    background: transparent;
    border: none;
    outline: none;
    resize: none;
    padding: 14px 16px;
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace;
    line-height: 1.6;
    color: #38bdf8;
    tab-size: 4;
    white-space: pre;
    overflow-x: auto;
    overflow-y: auto;
  }
  .code-editor.wrap {
    white-space: pre-wrap;
    word-break: break-word;
  }

  .inspector-footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 16px;
    border-top: 1px solid var(--card-border);
    background: var(--card-bg);
    flex-shrink: 0;
  }

  .inspector-hint {
    font-size: 0.68rem;
    color: var(--text-muted);
    font-family: monospace;
  }

  .footer-actions { display: flex; gap: 8px; }

  .action-btn {
    padding: 6px 16px;
    border-radius: 8px;
    border: 1px solid;
    font-size: 0.72rem;
    font-weight: 600;
    cursor: pointer;
    font-family: inherit;
    transition: all 0.15s;
  }
  .action-btn.copy {
    background: var(--panel-bg);
    border-color: var(--card-border);
    color: var(--text-main);
  }
  .action-btn.copy:hover { border-color: var(--accent-vis); }
  .action-btn.export {
    background: rgba(16, 185, 129, 0.15);
    border-color: rgba(16, 185, 129, 0.4);
    color: #10b981;
  }
  .action-btn.export:hover { background: rgba(16, 185, 129, 0.25); }
</style>
